package com;

import static com.app.*;
import java.awt.Color;
import static java.awt.Color.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class menuVendedor extends javax.swing.JFrame {

    ArrayList<Factura> facturas = new ArrayList();
    int xMouse, yMouse;
    double total = 0;
    ArrayList<Producto> productos = new ArrayList();
    ArrayList<Venta> ventas = new ArrayList();
    //ArrayList<Factura> facturas = new ArrayList();
    DefaultListModel datosIngresados = new DefaultListModel();
    int cantidadTotalProductos;

    public menuVendedor() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        asignarValoresTextField();
        datosIngresados = new DefaultListModel();
        listaProductosLLevarList.setModel(datosIngresados);
        abonoTextField.setEditable(false);
        numeroCuotas.setEditable(false);
        debeTextField.setEditable(false);
    }

    public void crearFactura(String Cliente, String Vendedor, String Fecha, String Estado, int CantProducto) throws IOException {
        Random rd = new Random();
        int idFactura = 0;
        boolean continuar;
        do {
            idFactura = rd.nextInt(100000) + 1;
            for (int i = 0; i < facturas.size(); i++) {
                if (facturas.get(i).getIdFactura() != idFactura) {
                    continuar = false;
                }
            }
        } while (continuar = true);
        facturas.add(new Factura(idFactura, Cliente, Vendedor, Fecha, Estado, CantProducto));
//        String texto = (String.valueOf(idFactura)) + "\n" + "Nombre del cliente:\t" + nombreProductoTextField.getText()
//                + "Nombre Vendedor:\t" + "Vendedor1\n" + "Fecha de compra:\t" + Fecha + "\n" + "Estado de la factura:\t" + Estado
//                + "\n" + "Cantidad de productos:\t" + String.valueOf(cantidadTotalProductos) + "\n" + "Total:\t" + totalPagarTextField.getText();
    }

    public void asignarValoresTextField() {
        fechaTextField.setEditable(false);
        fechaTextField.setText(fechaHoy());
        nombreProductoTextField.setEditable(false);
        app.llenarComboBox(medioPagoComboBox);
        productos = app.idProductos();
    }

    public void resetearCasillasTotal() {
        nombreClienteTextField.setText("");
        medioPagoComboBox.setSelectedIndex(0);
        idProductoTextField.setText("");
        fechaTextField.setText(fechaHoy());
        cantProductoTextField.setText("");
        precioUnitario.setText("");
        nombreProductoTextField.setText("");
        totalPagarTextField.setText("");
        numeroCuotas.setText("");
        debeTextField.setText("");
        abonoTextField.setText("");
    }

    public void resetearCasillasParcial() {
        idProductoTextField.setText("");
        cantProductoTextField.setText("");
        precioUnitario.setText("");
        nombreProductoTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuClose = new javax.swing.JPanel();
        closeButton = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        differentPages = new javax.swing.JTabbedPane();
        index = new javax.swing.JPanel();
        titleVendedor1 = new javax.swing.JLabel();
        realizarVenta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreClienteTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fechaTextField = new javax.swing.JTextField();
        medioPagoComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        productoPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        idProductoTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cantProductoTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        precioUnitario = new javax.swing.JTextField();
        agregarProductoButton = new javax.swing.JButton();
        nombreProductoTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalPagarTextField = new javax.swing.JTextField();
        abonoTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        debeTextField = new javax.swing.JTextField();
        realizarCompraButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductosLLevarList = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        numeroCuotas = new javax.swing.JTextField();
        verInventario = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        verVentas = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        verFacturas = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        menu = new javax.swing.JPanel();
        menuOptions = new javax.swing.JPanel();
        titleVendedor = new javax.swing.JLabel();
        menuOptionLabel = new javax.swing.JLabel();
        titleSeparator1 = new javax.swing.JSeparator();
        realizarVentaButton = new javax.swing.JPanel();
        realizarVentaLabel = new javax.swing.JLabel();
        monedaDolar = new javax.swing.JLabel();
        verInventarioButton = new javax.swing.JPanel();
        verInventarioLabel = new javax.swing.JLabel();
        cajaPaquete = new javax.swing.JLabel();
        verVentasButton = new javax.swing.JPanel();
        verVentasLabel = new javax.swing.JLabel();
        bolsaCompra = new javax.swing.JLabel();
        verFacturasButton = new javax.swing.JPanel();
        verFacturasLabel = new javax.swing.JLabel();
        factura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuClose.setBackground(new java.awt.Color(255, 255, 255));
        menuClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(255, 255, 255));

        closeLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(0, 0, 0));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeButtonLayout = new javax.swing.GroupLayout(closeButton);
        closeButton.setLayout(closeButtonLayout);
        closeButtonLayout.setHorizontalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        closeButtonLayout.setVerticalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        menuClose.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 45, 40));

        getContentPane().add(menuClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 0, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blanco.png"))); // NOI18N
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1000, 40));

        index.setBackground(new java.awt.Color(255, 255, 255));

        titleVendedor1.setFont(new java.awt.Font("Poppins Medium", 0, 32)); // NOI18N
        titleVendedor1.setForeground(new java.awt.Color(51, 51, 51));
        titleVendedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleVendedor1.setText(" MENÚ DE VENDEDOR");
        titleVendedor1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout indexLayout = new javax.swing.GroupLayout(index);
        index.setLayout(indexLayout);
        indexLayout.setHorizontalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(titleVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        indexLayout.setVerticalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(titleVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        differentPages.addTab("tab5", index);

        realizarVenta.setBackground(new java.awt.Color(255, 255, 255));
        realizarVenta.setPreferredSize(new java.awt.Dimension(700, 567));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total a pagar:");

        nombreClienteTextField.setBackground(new java.awt.Color(255, 255, 255));
        nombreClienteTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreClienteTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha");

        fechaTextField.setBackground(new java.awt.Color(255, 255, 255));
        fechaTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fechaTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fechaTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        medioPagoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        medioPagoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        medioPagoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioPagoComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Medio de pago");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre del cliente");

        productoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("idProducto");

        idProductoTextField.setBackground(new java.awt.Color(255, 255, 255));
        idProductoTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        idProductoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idProductoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductoTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre del producto");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cantidad a llevar");

        cantProductoTextField.setBackground(new java.awt.Color(255, 255, 255));
        cantProductoTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cantProductoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Precio Unidad:");

        precioUnitario.setEditable(false);
        precioUnitario.setBackground(new java.awt.Color(255, 255, 255));
        precioUnitario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        precioUnitario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarProductoButton.setText("Agregar Producto");
        agregarProductoButton.setPreferredSize(new java.awt.Dimension(124, 30));
        agregarProductoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarProductoButtonMouseClicked(evt);
            }
        });

        nombreProductoTextField.setBackground(new java.awt.Color(255, 255, 255));
        nombreProductoTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreProductoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout productoPanelLayout = new javax.swing.GroupLayout(productoPanel);
        productoPanel.setLayout(productoPanelLayout);
        productoPanelLayout.setHorizontalGroup(
            productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(261, 261, 261))
                    .addGroup(productoPanelLayout.createSequentialGroup()
                        .addComponent(idProductoTextField)
                        .addGap(217, 217, 217))
                    .addGroup(productoPanelLayout.createSequentialGroup()
                        .addGroup(productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(productoPanelLayout.createSequentialGroup()
                                .addComponent(cantProductoTextField)
                                .addGap(20, 20, 20)))
                        .addGap(18, 18, 18)
                        .addGroup(productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productoPanelLayout.createSequentialGroup()
                                .addComponent(agregarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(productoPanelLayout.createSequentialGroup()
                                .addGroup(productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(productoPanelLayout.createSequentialGroup()
                                        .addComponent(precioUnitario)
                                        .addGap(2, 2, 2)))
                                .addGap(75, 75, 75))))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(productoPanelLayout.createSequentialGroup()
                        .addComponent(nombreProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productoPanelLayout.setVerticalGroup(
            productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Abono:");

        totalPagarTextField.setBackground(new java.awt.Color(255, 255, 255));
        totalPagarTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        totalPagarTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        abonoTextField.setEditable(false);
        abonoTextField.setBackground(new java.awt.Color(255, 255, 255));
        abonoTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        abonoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Debe:");

        debeTextField.setEditable(false);
        debeTextField.setBackground(new java.awt.Color(255, 255, 255));
        debeTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        debeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        realizarCompraButton.setText("Realiza Compra");
        realizarCompraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarCompraButtonMouseClicked(evt);
            }
        });

        listaProductosLLevarList.setBackground(new java.awt.Color(255, 255, 255));
        listaProductosLLevarList.setForeground(new java.awt.Color(0, 0, 0));
        listaProductosLLevarList.setToolTipText("");
        jScrollPane2.setViewportView(listaProductosLLevarList);

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("N° Cuotas:");

        numeroCuotas.setEditable(false);
        numeroCuotas.setBackground(new java.awt.Color(255, 255, 255));
        numeroCuotas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        numeroCuotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout realizarVentaLayout = new javax.swing.GroupLayout(realizarVenta);
        realizarVenta.setLayout(realizarVentaLayout);
        realizarVentaLayout.setHorizontalGroup(
            realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realizarVentaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(realizarVentaLayout.createSequentialGroup()
                        .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addGap(139, 139, 139))
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(202, 202, 202))
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(112, 112, 112))
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medioPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addComponent(productoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(realizarVentaLayout.createSequentialGroup()
                        .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalPagarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(realizarVentaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(debeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(realizarCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        realizarVentaLayout.setVerticalGroup(
            realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realizarVentaLayout.createSequentialGroup()
                .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(realizarVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medioPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(realizarVentaLayout.createSequentialGroup()
                        .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(totalPagarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(abonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(numeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(debeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(realizarCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        differentPages.addTab("tab5", realizarVenta);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        verInventario.setViewportView(jTable1);

        differentPages.addTab("tab2", verInventario);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        verVentas.setViewportView(jTable2);

        differentPages.addTab("tab3", verVentas);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        verFacturas.setViewportView(jTable3);

        differentPages.addTab("tab4", verFacturas);

        getContentPane().add(differentPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 7, 700, 590));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setPreferredSize(new java.awt.Dimension(300, 500));
        menu.setLayout(new java.awt.BorderLayout());

        menuOptions.setBackground(new java.awt.Color(0, 0, 0));

        titleVendedor.setFont(new java.awt.Font("Poppins Medium", 0, 32)); // NOI18N
        titleVendedor.setForeground(new java.awt.Color(255, 255, 255));
        titleVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleVendedor.setText("VENDEDOR");

        menuOptionLabel.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        menuOptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuOptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuOptionLabel.setText("Menú de opciones");

        titleSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        titleSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        realizarVentaButton.setBackground(new java.awt.Color(0, 0, 0));
        realizarVentaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizarVentaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        realizarVentaLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        realizarVentaLabel.setForeground(new java.awt.Color(255, 255, 255));
        realizarVentaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        realizarVentaLabel.setText("Realizar Venta");
        realizarVentaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizarVentaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        realizarVentaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarVentaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                realizarVentaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                realizarVentaLabelMouseExited(evt);
            }
        });
        realizarVentaButton.add(realizarVentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 110, 44));

        monedaDolar.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        monedaDolar.setForeground(new java.awt.Color(255, 255, 255));
        monedaDolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monedaDolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monedas-de-dolar.png"))); // NOI18N
        monedaDolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        monedaDolar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        realizarVentaButton.add(monedaDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 45));

        verInventarioButton.setBackground(new java.awt.Color(0, 0, 0));
        verInventarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verInventarioButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verInventarioLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        verInventarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        verInventarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verInventarioLabel.setText("Ver inventario");
        verInventarioLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verInventarioLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verInventarioLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verInventarioLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verInventarioLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verInventarioLabelMouseExited(evt);
            }
        });
        verInventarioButton.add(verInventarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 110, 44));

        cajaPaquete.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        cajaPaquete.setForeground(new java.awt.Color(255, 255, 255));
        cajaPaquete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cajaPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja-del-paquete.png"))); // NOI18N
        cajaPaquete.setToolTipText("");
        cajaPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cajaPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verInventarioButton.add(cajaPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 45));

        verVentasButton.setBackground(new java.awt.Color(0, 0, 0));
        verVentasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verVentasButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verVentasLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        verVentasLabel.setForeground(new java.awt.Color(255, 255, 255));
        verVentasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verVentasLabel.setText("Ver ventas");
        verVentasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verVentasLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verVentasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verVentasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verVentasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verVentasLabelMouseExited(evt);
            }
        });
        verVentasButton.add(verVentasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 0, 110, 44));

        bolsaCompra.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        bolsaCompra.setForeground(new java.awt.Color(255, 255, 255));
        bolsaCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bolsaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bolsa-de-la-compra.png"))); // NOI18N
        bolsaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bolsaCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verVentasButton.add(bolsaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 0, 70, 45));

        verFacturasButton.setBackground(new java.awt.Color(0, 0, 0));
        verFacturasButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verFacturasLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        verFacturasLabel.setForeground(new java.awt.Color(255, 255, 255));
        verFacturasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verFacturasLabel.setText("Ver facturas");
        verFacturasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verFacturasLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verFacturasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verFacturasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verFacturasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verFacturasLabelMouseExited(evt);
            }
        });
        verFacturasButton.add(verFacturasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 110, 44));

        factura.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verFacturasButton.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 45));

        javax.swing.GroupLayout menuOptionsLayout = new javax.swing.GroupLayout(menuOptions);
        menuOptions.setLayout(menuOptionsLayout);
        menuOptionsLayout.setHorizontalGroup(
            menuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuOptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(titleSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(realizarVentaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(verInventarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(verVentasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(verFacturasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuOptionsLayout.setVerticalGroup(
            menuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOptionsLayout.createSequentialGroup()
                .addComponent(titleVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuOptionLabel)
                .addGap(42, 42, 42)
                .addComponent(titleSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(realizarVentaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(verInventarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(verVentasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(verFacturasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menu.add(menuOptions, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cambiarColor(JPanel panel, JLabel label, Color colorPanel, Color colorLabel) {
        panel.setBackground(colorPanel);
        label.setForeground(colorLabel);
    }
    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        cambiarColor(closeButton, closeLabel, RED, WHITE);
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        cambiarColor(closeButton, closeLabel, WHITE, BLACK);
    }//GEN-LAST:event_closeLabelMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void realizarVentaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaLabelMouseClicked
        differentPages.setSelectedIndex(1);
        cambiarColor(realizarVentaButton, realizarVentaLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
    }//GEN-LAST:event_realizarVentaLabelMouseClicked

    private void realizarVentaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaLabelMouseEntered
        cambiarColor(realizarVentaButton, realizarVentaLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_realizarVentaLabelMouseEntered

    private void realizarVentaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaLabelMouseExited
        if (differentPages.getSelectedIndex() == 1) {
            cambiarColor(realizarVentaButton, realizarVentaLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(realizarVentaButton, realizarVentaLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_realizarVentaLabelMouseExited

    private void verInventarioLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInventarioLabelMouseClicked
        differentPages.setSelectedIndex(2);
        cambiarColor(verInventarioButton, verInventarioLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(realizarVentaButton, realizarVentaLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
        verInventario();
    }//GEN-LAST:event_verInventarioLabelMouseClicked

    private void verInventarioLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInventarioLabelMouseEntered
        cambiarColor(verInventarioButton, verInventarioLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_verInventarioLabelMouseEntered

    private void verInventarioLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInventarioLabelMouseExited
        if (differentPages.getSelectedIndex() == 2) {
            cambiarColor(verInventarioButton, verInventarioLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        }

    }//GEN-LAST:event_verInventarioLabelMouseExited

    private void verVentasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verVentasLabelMouseClicked
        differentPages.setSelectedIndex(3);
        cambiarColor(verVentasButton, verVentasLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(realizarVentaButton, realizarVentaLabel, BLACK, WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
        verVentas();
    }//GEN-LAST:event_verVentasLabelMouseClicked

    private void verVentasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verVentasLabelMouseEntered
        cambiarColor(verVentasButton, verVentasLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_verVentasLabelMouseEntered

    private void verVentasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verVentasLabelMouseExited
        if (differentPages.getSelectedIndex() == 3) {
            cambiarColor(verVentasButton, verVentasLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        }

    }//GEN-LAST:event_verVentasLabelMouseExited

    private void verFacturasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasLabelMouseClicked
        differentPages.setSelectedIndex(4);
        cambiarColor(verFacturasButton, verFacturasLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(realizarVentaButton, realizarVentaLabel, BLACK, WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
    }//GEN-LAST:event_verFacturasLabelMouseClicked

    private void verFacturasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasLabelMouseEntered
        cambiarColor(verFacturasButton, verFacturasLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_verFacturasLabelMouseEntered

    private void verFacturasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasLabelMouseExited
        if (differentPages.getSelectedIndex() == 3) {
            cambiarColor(verFacturasButton, verFacturasLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_verFacturasLabelMouseExited


    private void agregarProductoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarProductoButtonMouseClicked
        int cantidad = Integer.parseInt(cantProductoTextField.getText());
        double precio = Double.parseDouble(precioUnitario.getText());
        int idProducto = Integer.parseInt(idProductoTextField.getText());
        for (int i = 0; i < productos.size(); i++) {
            if (productos.get(i).getIdProducto() == idProducto) {
                if(productos.get(i).getCantidad() >= cantidad) {
                    total = (cantidad * precio) + total;
                    totalPagarTextField.setText(String.valueOf(total));
                    String data = (idProductoTextField.getText() + " - "
                            + nombreProductoTextField.getText() + " - "
                            + cantProductoTextField.getText() + " x "
                            + precioUnitario.getText() + ":   "
                            + String.valueOf(cantidad * precio));
                    datosIngresados.addElement(data);
                    cantidad = productos.get(i).getCantidad() - cantidad;
                    productos.get(i).setCantidad(cantidad);
                    resetearCasillasParcial();
                    cantidadTotalProductos++;
                } else {
                    JOptionPane.showMessageDialog(null, "No hay stock sufienciente\n"
                            + "Stock: " + productos.get(i).getCantidad());
                }
            }
        }
    }//GEN-LAST:event_agregarProductoButtonMouseClicked

    private void idProductoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductoTextFieldActionPerformed
        int idProducto = Integer.parseInt(idProductoTextField.getText());
        int size = productos.size();
        for (int i = 0; i < size; i++) {
            if (productos.get(i).getIdProducto() == idProducto) {
                nombreProductoTextField.setText(productos.get(i).getNombre());
                precioUnitario.setText(String.valueOf(productos.get(i).getPrecio()));
            }
        }
    }//GEN-LAST:event_idProductoTextFieldActionPerformed

    private void nombreClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteTextFieldActionPerformed

    }//GEN-LAST:event_nombreClienteTextFieldActionPerformed

    private void medioPagoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioPagoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medioPagoComboBoxActionPerformed

    private void realizarCompraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarCompraButtonMouseClicked
        String nombre = nombreClienteTextField.getText();
        String fecha = fechaTextField.getText();
        String mediopago = (String)medioPagoComboBox.getSelectedItem();
        double totalpagar = Double.parseDouble(totalPagarTextField.getText());
        ventas.add(new Venta(nombre, fecha, mediopago, totalpagar));
        if (totalPagarTextField.getText().isBlank()
                || nombreClienteTextField.getText().isBlank()
                || medioPagoComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor llenar todos los"
                    + "campos necesarios para continuar");
        }
        if (medioPagoComboBox.getSelectedIndex() == 1) {
            abonoTextField.setText(totalPagarTextField.getText());
            debeTextField.setText("$ 0");
        }
        if (medioPagoComboBox.getSelectedIndex() == 2) {
            numeroCuotas.setEditable(true);
            abonoTextField.setEditable(true);
            double totalProductos = Double.parseDouble(totalPagarTextField.getText());
            double abono = Double.parseDouble(abonoTextField.getText());
            debeTextField.setText(String.valueOf(totalProductos - abono));
            do {
                JOptionPane.showMessageDialog(null, "Por favor llenar todos los"
                        + "campos necesarios para continuar");
            } while (abonoTextField.getText().isBlank() || numeroCuotas.getText().isBlank());
        }
    }//GEN-LAST:event_realizarCompraButtonMouseClicked

    public void verInventario(){
        int size = productos.size();
        String matriz [][] = new String[size][5];
        for(int i=0; i<size; i++){
            matriz [i][0] = String.valueOf(productos.get(i).getIdProducto());
            matriz [i][1] = productos.get(i).getNombre();
            matriz [i][2] = productos.get(i).getCategoria();
            matriz [i][3] = String.valueOf(productos.get(i).getPrecio());
            matriz [i][4] = String.valueOf(productos.get(i).getCantidad());
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel( matriz,
        new String [] {
                    "idProducto", "nombre", "categoria", "precio", "cantidad"
                }
        ));
    }
    public void verVentas(){
        int size = ventas.size();
        String matriz [][] = new String[size][4];
        for(int i=0; i<size; i++){
            matriz [i][0] = ventas.get(i).getNombre();
            matriz [i][1] = ventas.get(i).getFecha();
            matriz [i][2] = ventas.get(i).getMediopago();
            matriz [i][3] = String.valueOf(ventas.get(i).getTotalpagar());
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel( matriz,
        new String [] {
                    "nombreCliente", "fechaVenta", "medioPago", "totalPagar"
                }
        ));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abonoTextField;
    private javax.swing.JButton agregarProductoButton;
    private javax.swing.JLabel bolsaCompra;
    private javax.swing.JLabel cajaPaquete;
    private javax.swing.JTextField cantProductoTextField;
    private javax.swing.JPanel closeButton;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JTextField debeTextField;
    private javax.swing.JTabbedPane differentPages;
    private javax.swing.JLabel factura;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JLabel header;
    private javax.swing.JTextField idProductoTextField;
    private javax.swing.JPanel index;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JList<String> listaProductosLLevarList;
    private javax.swing.JComboBox<String> medioPagoComboBox;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuClose;
    private javax.swing.JLabel menuOptionLabel;
    private javax.swing.JPanel menuOptions;
    private javax.swing.JLabel monedaDolar;
    private javax.swing.JTextField nombreClienteTextField;
    private javax.swing.JTextField nombreProductoTextField;
    private javax.swing.JTextField numeroCuotas;
    private javax.swing.JTextField precioUnitario;
    private javax.swing.JPanel productoPanel;
    private javax.swing.JButton realizarCompraButton;
    private javax.swing.JPanel realizarVenta;
    private javax.swing.JPanel realizarVentaButton;
    private javax.swing.JLabel realizarVentaLabel;
    private javax.swing.JSeparator titleSeparator1;
    private javax.swing.JLabel titleVendedor;
    private javax.swing.JLabel titleVendedor1;
    private javax.swing.JTextField totalPagarTextField;
    private javax.swing.JScrollPane verFacturas;
    private javax.swing.JPanel verFacturasButton;
    private javax.swing.JLabel verFacturasLabel;
    private javax.swing.JScrollPane verInventario;
    private javax.swing.JPanel verInventarioButton;
    private javax.swing.JLabel verInventarioLabel;
    private javax.swing.JScrollPane verVentas;
    private javax.swing.JPanel verVentasButton;
    private javax.swing.JLabel verVentasLabel;
    // End of variables declaration//GEN-END:variables
}
