package com;

import com.menuVendedor;
import java.awt.Color;
import static java.awt.Color.*;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class menuAdmi extends javax.swing.JFrame {

    int xMouse, yMouse;
    ArrayList<Producto> productos = new ArrayList();
    ArrayList<Venta> ventas = new ArrayList();
    menuVendedor tablas = new menuVendedor();

    public menuAdmi() {
        initComponents();
        productos = tablas.productos;
        ventas = tablas.ventas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        crearVendedorButton = new javax.swing.JPanel();
        crearVendedorLabel = new javax.swing.JLabel();
        boligrafo = new javax.swing.JLabel();
        llamarProveedorButton = new javax.swing.JPanel();
        llamarProveedorLabel = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        verInventarioButton = new javax.swing.JPanel();
        verInventarioLabel = new javax.swing.JLabel();
        cajaPaquete = new javax.swing.JLabel();
        verVentasButton = new javax.swing.JPanel();
        verVentasLabel = new javax.swing.JLabel();
        bolsaCompra = new javax.swing.JLabel();
        verFacturasButton = new javax.swing.JPanel();
        verFacturasLabel = new javax.swing.JLabel();
        factura = new javax.swing.JLabel();
        titleSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        menuClose = new javax.swing.JPanel();
        closeButton = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        differentPages = new javax.swing.JTabbedPane();
        index = new javax.swing.JPanel();
        titleIndex = new javax.swing.JLabel();
        crearVendedor = new javax.swing.JPanel();
        llamarVendedor = new javax.swing.JPanel();
        verInventario = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        verVentas = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        verFacturas = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(0, 0, 0));

        crearVendedorButton.setBackground(new java.awt.Color(0, 0, 0));

        crearVendedorLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        crearVendedorLabel.setForeground(new java.awt.Color(255, 255, 255));
        crearVendedorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crearVendedorLabel.setText("Crear vendedor");
        crearVendedorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearVendedorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearVendedorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearVendedorLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearVendedorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearVendedorLabelMouseExited(evt);
            }
        });

        boligrafo.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        boligrafo.setForeground(new java.awt.Color(255, 255, 255));
        boligrafo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boligrafo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boligrafo.png"))); // NOI18N
        boligrafo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boligrafo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout crearVendedorButtonLayout = new javax.swing.GroupLayout(crearVendedorButton);
        crearVendedorButton.setLayout(crearVendedorButtonLayout);
        crearVendedorButtonLayout.setHorizontalGroup(
            crearVendedorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearVendedorButtonLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(boligrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearVendedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        crearVendedorButtonLayout.setVerticalGroup(
            crearVendedorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearVendedorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addGroup(crearVendedorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boligrafo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        llamarProveedorButton.setBackground(new java.awt.Color(0, 0, 0));

        llamarProveedorLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        llamarProveedorLabel.setForeground(new java.awt.Color(255, 255, 255));
        llamarProveedorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        llamarProveedorLabel.setText("Llamar proveedor");
        llamarProveedorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llamarProveedorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        llamarProveedorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llamarProveedorLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llamarProveedorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llamarProveedorLabelMouseExited(evt);
            }
        });

        telefono.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono.png"))); // NOI18N
        telefono.setToolTipText("");
        telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout llamarProveedorButtonLayout = new javax.swing.GroupLayout(llamarProveedorButton);
        llamarProveedorButton.setLayout(llamarProveedorButtonLayout);
        llamarProveedorButtonLayout.setHorizontalGroup(
            llamarProveedorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llamarProveedorButtonLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(llamarProveedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        llamarProveedorButtonLayout.setVerticalGroup(
            llamarProveedorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llamarProveedorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(llamarProveedorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telefono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        verInventarioButton.setBackground(new java.awt.Color(0, 0, 0));

        verInventarioLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        verInventarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        verInventarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verInventarioLabel.setText("Ver inventario");
        verInventarioLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verInventarioLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verInventarioLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verInventarioLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verInventarioLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verInventarioLabelMouseExited(evt);
            }
        });

        cajaPaquete.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        cajaPaquete.setForeground(new java.awt.Color(255, 255, 255));
        cajaPaquete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cajaPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja-del-paquete.png"))); // NOI18N
        cajaPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cajaPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout verInventarioButtonLayout = new javax.swing.GroupLayout(verInventarioButton);
        verInventarioButton.setLayout(verInventarioButtonLayout);
        verInventarioButtonLayout.setHorizontalGroup(
            verInventarioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verInventarioButtonLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cajaPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verInventarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        verInventarioButtonLayout.setVerticalGroup(
            verInventarioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verInventarioLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verInventarioButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cajaPaquete)
                .addContainerGap())
        );

        verVentasButton.setBackground(new java.awt.Color(0, 0, 0));

        verVentasLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        verVentasLabel.setForeground(new java.awt.Color(255, 255, 255));
        verVentasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verVentasLabel.setText("Ver ventas");
        verVentasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verVentasLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verVentasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verVentasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verVentasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verVentasLabelMouseExited(evt);
            }
        });

        bolsaCompra.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        bolsaCompra.setForeground(new java.awt.Color(255, 255, 255));
        bolsaCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bolsaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bolsa-de-la-compra.png"))); // NOI18N
        bolsaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bolsaCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout verVentasButtonLayout = new javax.swing.GroupLayout(verVentasButton);
        verVentasButton.setLayout(verVentasButtonLayout);
        verVentasButtonLayout.setHorizontalGroup(
            verVentasButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verVentasButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(bolsaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verVentasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        verVentasButtonLayout.setVerticalGroup(
            verVentasButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verVentasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(verVentasButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bolsaCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        verFacturasButton.setBackground(new java.awt.Color(0, 0, 0));

        verFacturasLabel.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        verFacturasLabel.setForeground(new java.awt.Color(255, 255, 255));
        verFacturasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verFacturasLabel.setText("Ver facturas");
        verFacturasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verFacturasLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verFacturasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verFacturasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verFacturasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verFacturasLabelMouseExited(evt);
            }
        });

        factura.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout verFacturasButtonLayout = new javax.swing.GroupLayout(verFacturasButton);
        verFacturasButton.setLayout(verFacturasButtonLayout);
        verFacturasButtonLayout.setHorizontalGroup(
            verFacturasButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verFacturasButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verFacturasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        verFacturasButtonLayout.setVerticalGroup(
            verFacturasButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verFacturasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(verFacturasButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(factura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        titleSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Menu de opciones");

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADMINISTRADOR");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSeparator1)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(crearVendedorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(llamarProveedorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verInventarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verVentasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verFacturasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(titleSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(crearVendedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(llamarProveedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verInventarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verVentasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verFacturasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 600));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blanco.png"))); // NOI18N
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        menuClose.setBackground(new java.awt.Color(255, 255, 255));
        menuClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(255, 255, 255));

        closeLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(0, 0, 0));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeButtonLayout = new javax.swing.GroupLayout(closeButton);
        closeButton.setLayout(closeButtonLayout);
        closeButtonLayout.setHorizontalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        closeButtonLayout.setVerticalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        menuClose.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 45, 40));

        background.add(menuClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 0, -1, -1));

        index.setBackground(new java.awt.Color(255, 255, 255));

        titleIndex.setFont(new java.awt.Font("Poppins Medium", 0, 32)); // NOI18N
        titleIndex.setForeground(new java.awt.Color(51, 51, 51));
        titleIndex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleIndex.setText("MENÚ ADMINISTRADOR");

        javax.swing.GroupLayout indexLayout = new javax.swing.GroupLayout(index);
        index.setLayout(indexLayout);
        indexLayout.setHorizontalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(titleIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(155, 155, 155))
        );
        indexLayout.setVerticalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(titleIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        differentPages.addTab("tab1", index);

        crearVendedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout crearVendedorLayout = new javax.swing.GroupLayout(crearVendedor);
        crearVendedor.setLayout(crearVendedorLayout);
        crearVendedorLayout.setHorizontalGroup(
            crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        crearVendedorLayout.setVerticalGroup(
            crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        differentPages.addTab("tab2", crearVendedor);

        llamarVendedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout llamarVendedorLayout = new javax.swing.GroupLayout(llamarVendedor);
        llamarVendedor.setLayout(llamarVendedorLayout);
        llamarVendedorLayout.setHorizontalGroup(
            llamarVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        llamarVendedorLayout.setVerticalGroup(
            llamarVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        differentPages.addTab("tab3", llamarVendedor);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        verInventario.setViewportView(jTable1);

        differentPages.addTab("tab4", verInventario);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        verVentas.setViewportView(jTable2);

        differentPages.addTab("tab5", verVentas);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        verFacturas.setViewportView(jTable3);

        differentPages.addTab("tab6", verFacturas);

        background.add(differentPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 7, 650, 593));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cambiarColor(JPanel panel, JLabel label, Color colorPanel, Color colorLabel) {
        panel.setBackground(colorPanel);
        label.setForeground(colorLabel);
    }
    private void crearVendedorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearVendedorLabelMouseClicked
        differentPages.setSelectedIndex(1);
        cambiarColor(crearVendedorButton, crearVendedorLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(llamarProveedorButton, llamarProveedorLabel, BLACK, WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
    }//GEN-LAST:event_crearVendedorLabelMouseClicked

    private void crearVendedorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearVendedorLabelMouseEntered
        cambiarColor(crearVendedorButton, crearVendedorLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_crearVendedorLabelMouseEntered

    private void crearVendedorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearVendedorLabelMouseExited
        if (differentPages.getSelectedIndex() == 1) {
            cambiarColor(crearVendedorButton, crearVendedorLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(crearVendedorButton, crearVendedorLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_crearVendedorLabelMouseExited

    private void llamarProveedorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llamarProveedorLabelMouseClicked
        differentPages.setSelectedIndex(2);
        cambiarColor(llamarProveedorButton, llamarProveedorLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(crearVendedorButton, crearVendedorLabel, BLACK, WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
    }//GEN-LAST:event_llamarProveedorLabelMouseClicked

    private void llamarProveedorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llamarProveedorLabelMouseEntered
        cambiarColor(llamarProveedorButton, llamarProveedorLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_llamarProveedorLabelMouseEntered

    private void llamarProveedorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llamarProveedorLabelMouseExited
        if (differentPages.getSelectedIndex() == 1) {
            cambiarColor(llamarProveedorButton, llamarProveedorLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(llamarProveedorButton, llamarProveedorLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_llamarProveedorLabelMouseExited

    private void verInventarioLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInventarioLabelMouseClicked
        differentPages.setSelectedIndex(3);
        cambiarColor(verInventarioButton, verInventarioLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(crearVendedorButton, crearVendedorLabel, BLACK, WHITE);
        cambiarColor(llamarProveedorButton, llamarProveedorLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
        verInventario();
    }//GEN-LAST:event_verInventarioLabelMouseClicked
    
    private void verInventarioLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInventarioLabelMouseEntered
        cambiarColor(verInventarioButton, verInventarioLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_verInventarioLabelMouseEntered

    private void verInventarioLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInventarioLabelMouseExited
        if (differentPages.getSelectedIndex() == 1) {
            cambiarColor(verInventarioButton, verInventarioLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_verInventarioLabelMouseExited

    private void verVentasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verVentasLabelMouseClicked
        differentPages.setSelectedIndex(4);
        cambiarColor(verVentasButton, verVentasLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(crearVendedorButton, crearVendedorLabel, BLACK, WHITE);
        cambiarColor(llamarProveedorButton, llamarProveedorLabel, BLACK, WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
        verVentas();
    }//GEN-LAST:event_verVentasLabelMouseClicked

    private void verVentasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verVentasLabelMouseEntered
        cambiarColor(verVentasButton, verVentasLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_verVentasLabelMouseEntered

    private void verVentasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verVentasLabelMouseExited
        if (differentPages.getSelectedIndex() == 1) {
            cambiarColor(verVentasButton, verVentasLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_verVentasLabelMouseExited

    private void verFacturasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasLabelMouseClicked
        differentPages.setSelectedIndex(5);
        cambiarColor(verFacturasButton, verFacturasLabel, new Color(153, 153, 153), WHITE);
        cambiarColor(crearVendedorButton, crearVendedorLabel, BLACK, WHITE);
        cambiarColor(llamarProveedorButton, llamarProveedorLabel, BLACK, WHITE);
        cambiarColor(verInventarioButton, verInventarioLabel, BLACK, WHITE);
        cambiarColor(verVentasButton, verVentasLabel, BLACK, WHITE);
    }//GEN-LAST:event_verFacturasLabelMouseClicked

    private void verFacturasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasLabelMouseEntered
        cambiarColor(verFacturasButton, verFacturasLabel, new Color(106, 105, 105), BLACK);
    }//GEN-LAST:event_verFacturasLabelMouseEntered

    private void verFacturasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasLabelMouseExited
        if (differentPages.getSelectedIndex() == 1) {
            cambiarColor(verFacturasButton, verFacturasLabel, new Color(153, 153, 153), WHITE);
        } else {
            cambiarColor(verFacturasButton, verFacturasLabel, BLACK, WHITE);
        }
    }//GEN-LAST:event_verFacturasLabelMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        cambiarColor(closeButton, closeLabel, WHITE, BLACK);
    }//GEN-LAST:event_closeLabelMouseExited

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        cambiarColor(closeButton, closeLabel, RED, WHITE);
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new quienEres().setVisible(true);
        });
    }//GEN-LAST:event_closeLabelMouseClicked

    public void verInventario(){
        int size = productos.size();
        String matriz [][] = new String[size][5];
        for(int i=0; i<size; i++){
            matriz [i][0] = String.valueOf(productos.get(i).getIdProducto());
            matriz [i][1] = productos.get(i).getNombre();
            matriz [i][2] = productos.get(i).getCategoria();
            matriz [i][3] = String.valueOf(productos.get(i).getPrecio());
            matriz [i][4] = String.valueOf(productos.get(i).getCantidad());
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel( matriz,
        new String [] {
                    "idProducto", "nombre", "categoria", "precio", "cantidad"
                }
        ));
    }
    
    public void verVentas(){
        int size = ventas.size();
        String matriz [][] = new String[size][4];
        for(int i=0; i<size; i++){
            matriz [i][0] = ventas.get(i).getNombre();
            matriz [i][1] = ventas.get(i).getFecha();
            matriz [i][2] = ventas.get(i).getMediopago();
            matriz [i][3] = String.valueOf(ventas.get(i).getTotalpagar());
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel( matriz,
        new String [] {
                    "nombreCliente", "fechaVenta", "medioPago", "totalPagar"
                }
        ));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel boligrafo;
    private javax.swing.JLabel bolsaCompra;
    private javax.swing.JLabel cajaPaquete;
    private javax.swing.JPanel closeButton;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel crearVendedor;
    private javax.swing.JPanel crearVendedorButton;
    private javax.swing.JLabel crearVendedorLabel;
    private javax.swing.JTabbedPane differentPages;
    private javax.swing.JLabel factura;
    private javax.swing.JLabel header;
    private javax.swing.JPanel index;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel llamarProveedorButton;
    private javax.swing.JLabel llamarProveedorLabel;
    private javax.swing.JPanel llamarVendedor;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuClose;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel titleIndex;
    private javax.swing.JSeparator titleSeparator1;
    private javax.swing.JScrollPane verFacturas;
    private javax.swing.JPanel verFacturasButton;
    private javax.swing.JLabel verFacturasLabel;
    private javax.swing.JScrollPane verInventario;
    private javax.swing.JPanel verInventarioButton;
    private javax.swing.JLabel verInventarioLabel;
    private javax.swing.JScrollPane verVentas;
    private javax.swing.JPanel verVentasButton;
    private javax.swing.JLabel verVentasLabel;
    // End of variables declaration//GEN-END:variables
}
